// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: gym.sql

package db

import (
	"context"
)

const createGym = `-- name: CreateGym :exec
INSERT INTO gyms (id, user_id, gym_name, team_name, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, gym_name, team_name, active
`

type CreateGymParams struct {
	ID       string
	UserID   string
	GymName  string
	TeamName string
	Active   bool
}

func (q *Queries) CreateGym(ctx context.Context, arg CreateGymParams) error {
	_, err := q.db.ExecContext(ctx, createGym,
		arg.ID,
		arg.UserID,
		arg.GymName,
		arg.TeamName,
		arg.Active,
	)
	return err
}

const getAllGyms = `-- name: GetAllGyms :many
SELECT id, user_id, gym_name, team_name, active FROM gyms
`

func (q *Queries) GetAllGyms(ctx context.Context) ([]Gym, error) {
	rows, err := q.db.QueryContext(ctx, getAllGyms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gym
	for rows.Next() {
		var i Gym
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GymName,
			&i.TeamName,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByGymName = `-- name: GetByGymName :one
SELECT id, user_id, gym_name, team_name, active FROM gyms WHERE gym_name = $1 LIMIT 1
`

func (q *Queries) GetByGymName(ctx context.Context, gymName string) (Gym, error) {
	row := q.db.QueryRowContext(ctx, getByGymName, gymName)
	var i Gym
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GymName,
		&i.TeamName,
		&i.Active,
	)
	return i, err
}

const getGymByID = `-- name: GetGymByID :one
SELECT id, user_id, gym_name, team_name, active
FROM gyms
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGymByID(ctx context.Context, id string) (Gym, error) {
	row := q.db.QueryRowContext(ctx, getGymByID, id)
	var i Gym
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GymName,
		&i.TeamName,
		&i.Active,
	)
	return i, err
}
