// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Student struct {
	ID         string
	UserID     sql.NullString
	Name       string
	Age        int32
	Graduation string
	Attendance sql.NullInt32
	Absences   sql.NullInt32
	Payment    bool
	Email      string
	Password   string
}

type User struct {
	ID             string
	Name           string
	Email          string
	Phone          string
	AcademyName    string
	InstructorBelt string
	Password       string
}
