// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: student.sql

package db

import (
	"context"
)

const createStudent = `-- name: CreateStudent :exec
INSERT INTO students (id, gym_id, name, graduation, active, training_time)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, gym_id, name, graduation, active, training_time
`

type CreateStudentParams struct {
	ID           string
	GymID        string
	Name         string
	Graduation   string
	Active       bool
	TrainingTime string
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent,
		arg.ID,
		arg.GymID,
		arg.Name,
		arg.Graduation,
		arg.Active,
		arg.TrainingTime,
	)
	return err
}
