apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  DB_DRIVER: postgres
  DB_HOST: 172.20.0.2
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: "88658710"
  DB_NAME: soltinho
  WEB_SERVER_PORT: "8000"
  JWT_SECRET: secret
  JWT_EXPIRESIN: "301"
